eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: 127.0.0.1
    port: 7001
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cuit.hyl.graduation.security_oauth.entity
server:
  port: 9055
spring:
  application:
    name: oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: MyHikariCP
    jdbc-url: jdbc:mysql://127.0.0.1:3306/graduation_authority?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    username: root

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  jpa:
    show-sql: true

  main:
    allow-bean-definition-overriding: true

#  redis:
#    lettuce:
#      pool:
#        max-active: 100
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0
#    sentinel:
#      master: mymaster
#      nodes: 192.168.91.130:26379
#
#  session:
#    store-type: redis

logging:
  level:
    cuit.hyl.graduation.security_oauth.dao: debug

