eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: 127.0.0.1
    port: 7001
    prefer-ip-address: true

server:
  port: 9050

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cuit.hyl.graduation.security_ui.entity
spring:
  application:
    name: ui
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: MyHikariCP
    jdbc-url: jdbc:mysql://127.0.0.1:3306/graduation_ui?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    username: root

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        maxActive: 100
        maxIdle: 10
        minIdle: 5
    password: 123456789
    port: 6379
    sentinel:
      master:
      nodes:

logging:
  level:
    cuit.hyl.graduation.project_ui.dao: debug

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9055/oauth/token
      user-authorization-uri: http://localhost:9055/oauth/authorize
    resource:
      token-info-uri: http://localhost:9055/oauth/check_token