eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: 127.0.0.1
    port: 7001
    prefer-ip-address: true

server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cuit.hyl.graduation.fastdfs.entity

spring:
  application:
    name: fastdfs
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: MyHikariCP
    jdbc-url: jdbc:mysql://127.0.0.1:3306/graduation_ui?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    username: root

  rabbitmq:
    host: 192.168.91.128
    port: 5672
    username: rabbit
    password: 123456

  redis:
    database: 0
    host: 192.168.91.128
    lettuce:
      pool:
        maxActive: 100
        maxIdle: 10
        minIdle: 5
    password:
#    password: 123456789
    port: 6379
#    sentinel:
#      master: mymaster
#      nodes: 192.168.91.128:26379, 192.168.91.128:26380, 192.168.91.128:26381
#    host: 127.0.0.1

  #  cloud:
#    stream:
#      rocketmq:
#        binder:
##          namesrv-addr:
#          name-server: 192.168.91.128:9876
#          bindings:
#          input: {consumer.orderly: true}
#      bindings:
#        output1: {destination: topic-codeEmail, content-type: application/json}
#        output2: {destination: topic-passwordChangeEmail, content-type: application/json}
#
#        input1: {destination: topic-codeEmail, content-type: application/json, group: group-Email}
#        input2: {destination: topic-passwordChangeEmail, content-type: application/json, group: group-Email}

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  mail:
    host: smtp.qq.com
    # 发送邮件的邮箱地址
    username: 2546615650@qq.com
    # 你的邮箱授权码
    password: jyyxlkxpptefebii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


fastdfs.base.url: http://192.168.91.128:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.91.128:22122
